Unstaged changes after reset:
M	api/src/main/java/org/killbill/billing/events/PaymentInfoInternalEvent.java
M	beatrix/src/test/java/org/killbill/billing/beatrix/util/PaymentChecker.java
M	jaxrs/src/main/java/org/killbill/billing/jaxrs/json/DirectTransactionJson.java
M	payment/src/main/java/org/killbill/billing/payment/api/DefaultDirectPayment.java
M	payment/src/main/java/org/killbill/billing/payment/api/DefaultDirectPaymentTransaction.java
M	payment/src/main/java/org/killbill/billing/payment/api/DefaultPaymentInfoEvent.java
M	payment/src/main/java/org/killbill/billing/payment/control/InvoicePaymentControlPluginApi.java
M	payment/src/main/java/org/killbill/billing/payment/core/DirectPaymentProcessor.java
M	payment/src/main/java/org/killbill/billing/payment/core/PaymentGatewayProcessor.java
M	payment/src/main/java/org/killbill/billing/payment/core/PaymentMethodProcessor.java
M	payment/src/main/java/org/killbill/billing/payment/core/ProcessorBase.java
M	payment/src/main/java/org/killbill/billing/payment/core/sm/AuthorizeOperation.java
M	payment/src/main/java/org/killbill/billing/payment/core/sm/CaptureOperation.java
M	payment/src/main/java/org/killbill/billing/payment/core/sm/CreditOperation.java
M	payment/src/main/java/org/killbill/billing/payment/core/sm/DirectPaymentAutomatonDAOHelper.java
M	payment/src/main/java/org/killbill/billing/payment/core/sm/DirectPaymentAutomatonRunner.java
M	payment/src/main/java/org/killbill/billing/payment/core/sm/DirectPaymentEnteringStateCallback.java
M	payment/src/main/java/org/killbill/billing/payment/core/sm/DirectPaymentOperation.java
M	payment/src/main/java/org/killbill/billing/payment/core/sm/OperationCallbackBase.java
D	payment/src/main/java/org/killbill/billing/payment/core/sm/PluginOperationBase.java
M	payment/src/main/java/org/killbill/billing/payment/core/sm/PurchaseOperation.java
M	payment/src/main/java/org/killbill/billing/payment/core/sm/RefundOperation.java
M	payment/src/main/java/org/killbill/billing/payment/core/sm/RetryAuthorizeOperationCallback.java
M	payment/src/main/java/org/killbill/billing/payment/core/sm/RetryCaptureOperationCallback.java
M	payment/src/main/java/org/killbill/billing/payment/core/sm/RetryCreditOperationCallback.java
M	payment/src/main/java/org/killbill/billing/payment/core/sm/RetryOperationCallback.java
M	payment/src/main/java/org/killbill/billing/payment/core/sm/RetryPurchaseOperationCallback.java
M	payment/src/main/java/org/killbill/billing/payment/core/sm/RetryRefundOperationCallback.java
M	payment/src/main/java/org/killbill/billing/payment/core/sm/RetryVoidOperationCallback.java
M	payment/src/main/java/org/killbill/billing/payment/core/sm/VoidOperation.java
D	payment/src/main/java/org/killbill/billing/payment/core/sm/retryPluginOperation.java
M	payment/src/main/java/org/killbill/billing/payment/dao/DefaultPaymentDao.java
M	payment/src/main/java/org/killbill/billing/payment/dao/PaymentAttemptSqlDao.java
M	payment/src/main/java/org/killbill/billing/payment/dao/PaymentDao.java
M	payment/src/main/java/org/killbill/billing/payment/dao/PaymentModelDao.java
M	payment/src/main/java/org/killbill/billing/payment/dao/PaymentTransactionModelDao.java
M	payment/src/main/java/org/killbill/billing/payment/dispatcher/PluginDispatcher.java
M	payment/src/main/resources/org/killbill/billing/payment/ddl.sql
M	payment/src/test/java/org/killbill/billing/payment/api/TestEventJson.java
M	payment/src/test/java/org/killbill/billing/payment/api/TestPaymentApi.java
M	payment/src/test/java/org/killbill/billing/payment/api/TestPaymentApiNoDB.java
M	payment/src/test/java/org/killbill/billing/payment/core/TestDirectPaymentProcessor.java
M	payment/src/test/java/org/killbill/billing/payment/core/sm/MockRetryAuthorizeOperationCallback.java
M	payment/src/test/java/org/killbill/billing/payment/core/sm/TestDirectPaymentAutomatonDAOHelper.java
M	payment/src/test/java/org/killbill/billing/payment/core/sm/TestDirectPaymentEnteringStateCallback.java
M	payment/src/test/java/org/killbill/billing/payment/core/sm/TestDirectPaymentLeavingStateCallback.java
M	payment/src/test/java/org/killbill/billing/payment/core/sm/TestDirectPaymentOperation.java
M	payment/src/test/java/org/killbill/billing/payment/core/sm/TestPluginOperation.java
M	payment/src/test/java/org/killbill/billing/payment/core/sm/TestRetryableDirectPayment.java
M	payment/src/test/java/org/killbill/billing/payment/dao/MockPaymentDao.java
M	payment/src/test/java/org/killbill/billing/payment/dao/TestDefaultPaymentDao.java
M	payment/src/test/java/org/killbill/billing/payment/dao/TestPaymentDao.java
M	payment/src/test/java/org/killbill/billing/payment/dispatcher/TestPluginDispatcher.java
M	util/src/main/java/org/killbill/billing/util/audit/DefaultAccountAuditLogs.java
