drop index _invoice_payment_control_plugin_auto_pay_off_account on _invoice_payment_control_plugin_auto_pay_off;
alter table _invoice_payment_control_plugin_auto_pay_off rename invoice_payment_control_plugin_auto_pay_off;
create INDEX invoice_payment_control_plugin_auto_pay_off_account on invoice_payment_control_plugin_auto_pay_off(account_id);
